name: 'GitHub Push'
description: 'Pushing changes to remote git repository.'
author: 'synoa'
branding:
  icon: upload-cloud
  color: green
inputs:
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
  git_args:
    description: "Additional arguments to add to git. Will be added at the end of command"
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
